# Generated by Django 5.1.1 on 2025-02-09 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refuel',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 2, 9, 20, 58, 47, 122366, tzinfo=datetime.timezone.utc)),
        ),
    ]
